apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentsurvey-deployment
  labels:
    app: studentsurvey
spec:
  replicas: 3
  selector:
    matchLabels:
      app: studentsurvey
  template:
    metadata:
      labels:
        app: studentsurvey
    spec:
      containers:
        - name: studentsurvey
          image: ${IMAGE}:${TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: studentsurvey-service
  labels:
    app: studentsurvey
spec:
  type: NodePort
  selector:
    app: studentsurvey
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
