apiVersion: v1
kind: Service
metadata:
  name: studentsurvey-service
  labels:
    app: studentsurvey
spec:
  type: NodePort
  selector:
    app: studentsurvey
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
